"""Validation helpers for generated shopping responses."""

from __future__ import annotations

import re

from shared.events.schemas import DecisionRanked, RankedProduct

URL_PATTERN = re.compile(r"https?://[^\s)]+")
INTRO_PATTERN = re.compile(
    r"INTRO\s*:\s*(?P<intro>.*?)(?=\n\s*BEST_REASON\s*:|\n\s*WHY_THIS_ORDER\s*:|\n\s*NEXT_STEP\s*:|$)",
    re.IGNORECASE | re.DOTALL,
)
BEST_REASON_PATTERN = re.compile(
    r"BEST_REASON\s*:\s*(?P<reason>.*?)(?=\n\s*WHY_THIS_ORDER\s*:|\n\s*NEXT_STEP\s*:|$)",
    re.IGNORECASE | re.DOTALL,
)
WHY_PATTERN = re.compile(
    r"WHY_THIS_ORDER\s*:\s*(?P<why>.*?)(?=\n\s*NEXT_STEP\s*:|$)",
    re.IGNORECASE | re.DOTALL,
)
NEXT_STEP_PATTERN = re.compile(r"NEXT_STEP\s*:\s*(?P<next>.*)$", re.IGNORECASE | re.DOTALL)


class ResponseValidationError(ValueError):
    """Raised when an LLM response drops or changes critical product facts."""


def materialize_llm_response(event: DecisionRanked, llm_text: str, *, fallback_message: str) -> str:
    """Compose LLM style text with exact product facts generated by code."""
    intro, best_reason, why_this_order, next_step = _parse_llm_sections(llm_text)
    if intro or best_reason or why_this_order or next_step:
        from agents.agent_generator.agent import build_composed_message

        if not event.products:
            return intro or next_step or fallback_message
        if not intro:
            intro = _default_intro(event)
        if not best_reason:
            best_reason = _default_best_reason(event.products[0])
        return build_composed_message(
            event.products,
            intro=intro,
            best_reason=best_reason,
            why_this_order=why_this_order,
            next_step=next_step,
        )
    return llm_text.strip() or fallback_message


def validate_response(event: DecisionRanked, message: str) -> None:
    if not message.strip():
        raise ResponseValidationError("empty_response")
    if not event.products:
        return

    allowed_urls = {str(product.url).rstrip("/") for product in event.products[:3]}
    mentioned_urls = {url.rstrip("/.,") for url in URL_PATTERN.findall(message)}
    unknown_urls = mentioned_urls - allowed_urls
    if unknown_urls:
        raise ResponseValidationError(f"unknown_urls:{sorted(unknown_urls)}")

    for product in event.products[:3]:
        _validate_product_facts(product, message)


def _parse_llm_sections(text: str) -> tuple[str | None, str | None, str | None, str | None]:
    stripped = text.strip()
    intro_match = INTRO_PATTERN.search(stripped)
    reason_match = BEST_REASON_PATTERN.search(stripped)
    why_match = WHY_PATTERN.search(stripped)
    next_match = NEXT_STEP_PATTERN.search(stripped)
    intro = _clean_section(intro_match.group("intro")) if intro_match else None
    reason = _clean_section(reason_match.group("reason")) if reason_match else None
    why = _clean_section(why_match.group("why")) if why_match else None
    next_step = _clean_section(next_match.group("next")) if next_match else None
    return intro, reason, why, next_step


def _clean_section(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip().strip('"')


def _default_intro(event: DecisionRanked) -> str:
    count = min(3, len(event.products))
    return f"I found {count} good option{'s' if count != 1 else ''} for you:"


def _default_best_reason(product: RankedProduct) -> str:
    return (
        f"Best choice: {product.title} because it has the strongest overall score, "
        f"a good price, and availability marked as {product.availability}."
    )


def _validate_product_facts(product: RankedProduct, message: str) -> None:
    normalized = message.lower()
    title_tokens = [token for token in re.split(r"\W+", product.title.lower()) if len(token) >= 3]
    if title_tokens and not any(token in normalized for token in title_tokens[:4]):
        raise ResponseValidationError(f"missing_title:{product.title}")

    price_text = f"{product.price:g}"
    if price_text not in message:
        raise ResponseValidationError(f"missing_price:{price_text}")

    if product.source.lower() not in normalized:
        raise ResponseValidationError(f"missing_source:{product.source}")

    if str(product.url).rstrip("/") not in message.replace("/\n", "/"):
        raise ResponseValidationError(f"missing_url:{product.url}")
