"""Validation helpers for generated shopping responses."""

from __future__ import annotations

import re

from agents.agent_generator.tools.behavior_analyzer import infer_language
from agents.agent_generator.tools.text_safety import REPETITION_PATTERN, is_usable_prose, sanitize_llm_prose
from shared.events.schemas import DecisionRanked, RankedProduct

URL_PATTERN = re.compile(r"https?://[^\s)]+")
SECTION_NAMES = (
    "GENERAL_REPLY",
    "INTRO",
    "PRODUCT_HEADER",
    "CLOSING",
    "PRICE_LABEL",
    "SOURCE_LABEL",
    "SCORE_LABEL",
    "LINK_LABEL",
    "BEST_REASON",
    "WHY_THIS_ORDER",
    "NEXT_STEP",
)
SECTION_PATTERN = re.compile(
    rf"^({'|'.join(SECTION_NAMES)})\s*:\s*(.*?)(?=^({'|'.join(SECTION_NAMES)})\s*:|\Z)",
    re.IGNORECASE | re.DOTALL | re.MULTILINE,
)


class ResponseValidationError(ValueError):
    """Raised when an LLM response drops or changes critical product facts."""


def materialize_llm_response(event: DecisionRanked, llm_text: str, *, fallback_message: str) -> str:
    """Compose LLM style text with exact product facts generated by code."""
    sections = _parse_llm_sections(llm_text)
    if sections:
        if not event.products:
            general_reply = sections.get("general_reply") or sections.get("intro") or fallback_message
            cleaned = sanitize_llm_prose(general_reply, max_length=400)
            return cleaned if is_usable_prose(cleaned, max_length=400) else fallback_message

        from agents.agent_generator.agent import build_composed_message

        closing = sections.get("closing") or _join_closing_sections(sections)
        intro = sections.get("intro")
        product_header = sections.get("product_header")
        if product_header and _header_contains_product_facts(product_header):
            product_header = None

        intro = _resolve_intro(event, intro)
        closing = _resolve_closing(event, closing)
        product_style = "natural" if not any(
            sections.get(key) for key in ("price_label", "source_label", "score_label", "link_label")
        ) else "labeled"
        labels = {
            "price": sections.get("price_label") or "Price",
            "source": sections.get("source_label") or "Source",
            "score": sections.get("score_label") or "Score",
            "link": sections.get("link_label") or "Link",
        }
        return build_composed_message(
            event.products,
            intro=intro,
            product_header=product_header,
            best_reason=closing,
            why_this_order=None,
            next_step=None,
            labels=labels,
            product_style=product_style,
        )
    return llm_text.strip() or fallback_message


def validate_response(event: DecisionRanked, message: str) -> None:
    if not message.strip():
        raise ResponseValidationError("empty_response")
    if not event.products:
        return

    allowed_urls = {str(product.url).rstrip("/") for product in event.products[:3]}
    mentioned_urls = {url.rstrip("/.,") for url in URL_PATTERN.findall(message)}
    unknown_urls = mentioned_urls - allowed_urls
    if unknown_urls:
        raise ResponseValidationError(f"unknown_urls:{sorted(unknown_urls)}")

    for product in event.products[:3]:
        _validate_product_facts(product, message)


def _parse_llm_sections(text: str) -> dict[str, str]:
    section_limits = {
        "intro": 180,
        "product_header": 60,
        "closing": 320,
        "general_reply": 400,
        "best_reason": 220,
        "why_this_order": 180,
        "next_step": 180,
    }
    sections: dict[str, str] = {}
    for match in SECTION_PATTERN.finditer(text.strip()):
        key = match.group(1).lower()
        value = _clean_section(match.group(2), max_length=section_limits.get(key, 320))
        if value:
            sections[key] = value
    return sections


def _clean_section(value: str, *, max_length: int = 320) -> str:
    return sanitize_llm_prose(value, max_length=max_length)


def _resolve_intro(event: DecisionRanked, intro: str | None) -> str:
    cleaned = _clean_section(intro or "", max_length=180)
    if is_usable_prose(cleaned, max_length=180):
        return cleaned
    return _default_intro(event)


def _resolve_closing(event: DecisionRanked, closing: str | None) -> str:
    raw = closing or ""
    if raw and REPETITION_PATTERN.search(raw):
        return _default_closing(event)
    cleaned = _clean_section(raw, max_length=320)
    if is_usable_prose(cleaned, max_length=320) and _ends_cleanly(cleaned):
        return cleaned
    return _default_closing(event)


def _ends_cleanly(text: str) -> bool:
    stripped = text.strip()
    return bool(stripped) and stripped[-1] in ".!?؟…"


def _join_closing_sections(sections: dict[str, str]) -> str:
    parts = [
        sections.get("best_reason"),
        sections.get("why_this_order"),
        sections.get("next_step"),
    ]
    return " ".join(part.strip() for part in parts if part and part.strip())


def _header_contains_product_facts(header: str) -> bool:
    lowered = header.lower()
    if URL_PATTERN.search(header):
        return True
    if re.search(r"\b\d{3,}\b", header):
        return True
    if any(token in lowered for token in ("http", "mad", "price:", "source:", "score:", "link:")):
        return True
    return len(header) > 80


def _default_intro(event: DecisionRanked) -> str:
    count = min(3, len(event.products))
    language = infer_language(event.user_text or "")
    if language == "darija":
        return f"L9it lik {count} option{'s' if count != 1 else ''} mzyanin."
    if language == "fr":
        suffix = "s" if count != 1 else ""
        return f"J'ai trouve {count} bonne option{suffix} pour toi."
    if language == "ar":
        return f"وجدت {count} خيارات مناسبة لك."
    return f"I found {count} good option{'s' if count != 1 else ''} for you."


def _default_closing(event: DecisionRanked) -> str:
    language = infer_language(event.user_text or "")
    if language == "darija":
        return (
            "L'option 1 hiya l'ahsen: score 3ali, taman mzyan, w kayna f stock. "
            "Rattbehom 3la value, thiqa, w disponibilite. "
            "Bda b option 1 w verify seller w delivery qbel ma tchri."
        )
    if language == "fr":
        return (
            "L'option 1 est la meilleure: bon score, bon prix, et disponible. "
            "Je les ai classees selon le rapport qualite-prix, la confiance et la disponibilite. "
            "Commence par l'option 1 et verifie le vendeur avant d'acheter."
        )
    if language == "ar":
        return (
            "الخيار الأول هو الأفضل: تقييم أعلى وسعر مناسب ومتوفر. "
            "رتبتها حسب القيمة والثقة والجودة والتوفر. "
            "ابدأ بالخيار الأول وتحقق من البائع قبل الشراء."
        )
    product = event.products[0]
    return _default_best_reason(product)


def _default_best_reason(product: RankedProduct) -> str:
    return (
        f"Best choice: {product.title} because it has the strongest overall score, "
        f"a good price, and availability marked as {product.availability}."
    )


def _validate_product_facts(product: RankedProduct, message: str) -> None:
    normalized = message.lower()
    title_tokens = [token for token in re.split(r"\W+", product.title.lower()) if len(token) >= 3]
    if title_tokens and not any(token in normalized for token in title_tokens[:4]):
        raise ResponseValidationError(f"missing_title:{product.title}")

    price_text = f"{product.price:g}"
    if price_text not in message:
        raise ResponseValidationError(f"missing_price:{price_text}")

    if product.source.lower() not in normalized:
        raise ResponseValidationError(f"missing_source:{product.source}")

    if str(product.url).rstrip("/") not in message.replace("/\n", "/"):
        raise ResponseValidationError(f"missing_url:{product.url}")
