apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
images:
  - name: smart-shopper/service
    newName: smart-shopper/service
    newTag: dev
  - name: smart-shopper/ner
    newName: smart-shopper/ner
    newTag: dev
